### ISSUE TITLE
Plugin when there aren't any posts

### ISSUE THREAD

**Issue by ivanram93** [tiptoppress/category-posts-widget#175]
I think that the plugin does't have the validation because it doesn't display a text saying something like: "There are aren't posts on this category."

Thanks.

**Comment by markkap** [comment]
@DanielFloeter any objection? if no, lets set it for 4.9

**Comment by DanielFloeter** [comment]
We've heard this point before.

@ivanram93 Why is your category empty?
A category is actually there to be filled. Actually only when creating a page is a category without blog posts available.

**Comment by markkap** [comment]
If we will implement date filters (actually not sure now ...), the category might be empty because there are simply no posts matching the date. I agree that for the simple use case of the plugin it should not make much sense.

But we probably do need such a functionality for "pro" and do not see why not to have it in the free version as well.
